apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:11Z"
    name: attachdetach-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:09Z"
    name: certificate-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:10Z"
    name: clusterrole-aggregation-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4yPzU7rQAxGX+XqW6e5+WsTRmLRNUsk9s6MQ4ckdpVxg1DVd0fZIaECS+vYR8dX0Dm+8JKiChzWEhnGKAEOz7ys0fPRe72IIcPMRoGM4K4gETWyqJK2Ufs39pbY8iVq7sls4jzq/7iJkN3l+i687F7XEQ5jnb6Qtcz+PUUJj8cQVH5VCM0MB68LB0l/Wk9n8tvNeOl5lz6S8Yxbhol6nn586kTpBIfec9XV1UPXlWXb1FTU3YH6fVkM1XBoeWibqin8vt2k3/LuBtw+AwAA///oKnY0kgEAAA
      objectset.rio.cattle.io/id: ""
      objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
      objectset.rio.cattle.io/owner-name: coredns
      objectset.rio.cattle.io/owner-namespace: kube-system
    creationTimestamp: "2024-08-16T13:37:58Z"
    labels:
      objectset.rio.cattle.io/hash: bce283298811743a0386ab510f2f67ef74240c57
    name: coredns
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:11Z"
    name: cronjob-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:10Z"
    name: daemon-set-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:09Z"
    name: deployment-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:10Z"
    name: disruption-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:09Z"
    name: endpoint-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:09Z"
    name: endpointslice-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:37:58Z"
    name: endpointslicemirroring-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:10Z"
    name: ephemeral-volume-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:37:58Z"
    name: expand-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:08Z"
    name: generic-garbage-collector
    namespace: kube-system
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4ySQY/TMBCF/wqas12apiFdSxwQHJA4IMGKC+Iwdl62Jo5d2ZMitMp/R4kqdmFV2OPYM988vTf3xCf/Bbn4FMnQuSJFPEka0xTlM/LZO7xxbqlu04BIRvIERYOPHRn6s4MUjRDuWJjMPXGMSVh8imUpk/0OJwWyyT5tHIsEbHx66RfQEWHULkXJKQRk7Y6cRWfc+SJ5ZZC6Skg/IrK+Ow8X0KOvc6VefPCxe/0eYXy7QP/LiTyCDElm9H54Vns5sVtmhslCl59FMNKsyGWs0m/9iCI8nsjEKQRFgS3CP005cjmSIbftb1pwy7sGdQfXVjdN61qud/uK60Nfo+kZTb9su+henXwQf02eolX+J/TIiA6FzNe/juGJlaTIhuSGj8vkOwSsuZieQ4Gih/R+P12u5LH3T9yd1vxt1bR2/2qnm711el8dOn3gxmq73dYHtM71FdP8bZ5/BQAA//+vzWRSsQIAAA
      objectset.rio.cattle.io/id: helm-controller-chart-registration
      objectset.rio.cattle.io/owner-gvk: helm.cattle.io/v1, Kind=HelmChart
      objectset.rio.cattle.io/owner-name: traefik
      objectset.rio.cattle.io/owner-namespace: kube-system
    creationTimestamp: "2024-08-16T13:38:01Z"
    labels:
      objectset.rio.cattle.io/hash: c0f97ea7a25e3dec71957c7a3241a38f3e5fae5f
    name: helm-traefik
    namespace: kube-system
    ownerReferences:
    - apiVersion: helm.cattle.io/v1
      blockOwnerDeletion: false
      controller: false
      kind: HelmChart
      name: traefik
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4yST4/TMBDFvwqas12adEMTSxwQHJA4IMGKC+IwGY+3Jv5T2ZMitOp3R4kq2AUKexzb8/PMe+8e8Og/cak+JzBwakABzpJjnpN85HLyxK+Iluo2T5zASJlZweSTBQOPX4CCyIIWBcHcA6aUBcXnVJcyj1+ZpLJsis8bQpHAG5+f+wV04BA15SQlh8BF0wGL6MJ3vkpZGaCuEvK3xEXfnaYL6MHVqVHP3vlkX77lEF8v0P9yEkYGA1KQnZ80FfuklnpEWvqmeWRdv1fhCGcFVHgd/9ZHroLxCCbNISgIOHL4pzAHrAcwcNM7t7Md7ZpmP+72rSNL2G2H/dC5wbX7bYtu2w3t8ttl9lXNxwtcG1HBusIHdlw4EVcwn38LxR+SgoIxZJreL51vOPDqj3EYKiv45eLPo0taHnrwV5XnNQsDd5Zw12vnWqtvCHvdj2g1OuuGhhruXzCcv5zPPwIAAP//0CjyiL0CAAA
      objectset.rio.cattle.io/id: helm-controller-chart-registration
      objectset.rio.cattle.io/owner-gvk: helm.cattle.io/v1, Kind=HelmChart
      objectset.rio.cattle.io/owner-name: traefik-crd
      objectset.rio.cattle.io/owner-namespace: kube-system
    creationTimestamp: "2024-08-16T13:38:01Z"
    labels:
      objectset.rio.cattle.io/hash: 48ff3d5c3117b372fcdca509795f9f2702af0592
    name: helm-traefik-crd
    namespace: kube-system
    ownerReferences:
    - apiVersion: helm.cattle.io/v1
      blockOwnerDeletion: false
      controller: false
      kind: HelmChart
      name: traefik-crd
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:10Z"
    name: horizontal-pod-autoscaler
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:08Z"
    name: job-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:37:58Z"
    name: legacy-service-account-token-cleaner
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4yQQUvEMBCF/4rMuVlb05YS8LBnj4L3aTLdxraZkpmtyLL/XYogelj1ODzex5vvArjGF8oSOYGDrYICppgCOHimvEVPR+/5nBQKWEgxoCK4C2BKrKiRk+wn96/kVUgPOfLBo+pMh8j3cQdBcTPnt0TZnLYJHExWviVbVdw9xRQejyFw+hORcCFwMLPH2YhyxhP9qyQr+r05nXsy8i5KC1wLmLGn+dfXRpQRHFSdHWzj22YYem/Ltm5LO9R2qJquDJ1vO3wI2Id6h/4YuaKOZs28xd09ZSOfvg1+Cb+57/oRAAD///h+7Ma3AQAA
      objectset.rio.cattle.io/id: ""
      objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
      objectset.rio.cattle.io/owner-name: local-storage
      objectset.rio.cattle.io/owner-namespace: kube-system
    creationTimestamp: "2024-08-16T13:37:58Z"
    labels:
      objectset.rio.cattle.io/hash: 183f35c65ffbc3064603f43f1580d8c68a2dabd4
    name: local-path-provisioner-service-account
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4TPPU/DMBDG8a+Cbk4CeSlRLDF0ZkRiv/ieUJPEjuxrUFX1u6PAwlDa0X6kn/53Jl7cO2JywZOhtaSMRueFDL0hrs5ib204eqWMZigLK5M5E3sflNUFn7Zn6D9hNUGL6EJhWXVC4cKj2yDK/t3Dl0fMP9aRDI11+rOsZfbw6ry87EWCv0t4nkFmS4zOpjwhroi5YJnCacZP/n0gLWw3ZTz2yNMpKWa6ZDRxj+nmmQdOBzKE8glVs0NZo3nmttrZTkSkGTr0Vd0NZdO2bTPIhl4Npt//qx2X7wAAAP//ruNhwKsBAAA
      objectset.rio.cattle.io/id: ""
      objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
      objectset.rio.cattle.io/owner-name: metrics-server-deployment
      objectset.rio.cattle.io/owner-namespace: kube-system
    creationTimestamp: "2024-08-16T13:37:59Z"
    labels:
      objectset.rio.cattle.io/hash: e10e245e13e46a725c9dddd4f9eb239f147774fd
    name: metrics-server
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:11Z"
    name: namespace-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:37:58Z"
    name: node-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:08Z"
    name: persistent-volume-binder
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:08Z"
    name: pod-garbage-collector
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:09Z"
    name: pv-protection-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:37:58Z"
    name: pvc-protection-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:08Z"
    name: replicaset-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:09Z"
    name: replication-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:08Z"
    name: resourcequota-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:09Z"
    name: root-ca-cert-publisher
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:37:58Z"
    name: service-account-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:37:58Z"
    name: statefulset-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:01Z"
    name: svclb
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:37:58Z"
    name: token-cleaner
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: traefik
      meta.helm.sh/release-namespace: kube-system
    creationTimestamp: "2024-08-16T13:38:36Z"
    labels:
      app.kubernetes.io/instance: traefik-kube-system
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: traefik
      helm.sh/chart: traefik-25.0.3_up25.0.0
    name: traefik
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:08Z"
    name: ttl-after-finished-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:38:08Z"
    name: ttl-controller
    namespace: kube-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-16T13:37:58Z"
    name: validatingadmissionpolicy-status-controller
    namespace: kube-system
kind: List
metadata:
